# Generated by Django 5.0.2 on 2024-03-05 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('login_name', models.CharField(max_length=254, primary_key=True, serialize=False, verbose_name='username used to login')),
                ('nickname', models.CharField(max_length=64, verbose_name='name shown')),
                ('registration_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('creation_datetime', models.DateTimeField()),
                ('chore_description', models.CharField(max_length=256)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choreman.user')),
            ],
        ),
    ]
